### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by IodizedSalt** [IodizedSalt/babite-api#4]

**Comment by hajduboti** [comment]
_Probably handled by Cognito_

TODO: Research

**Comment by IodizedSalt** [comment]
> _Probably handled by Cognito_
> 
> TODO: Research

- [ ] https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html

- [ ] https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ConfirmForgotPassword.html
